# App Configurations
APP_RELOAD = 'APP_RELOAD'
APP_HOST = 'APP_HOST'
APP_PORT = 'APP_PORT'
APP_WORKERS = 'APP_WORKERS'

# Memcached Configurations
MEMCACHED_HOST = 'MEMCACHED_HOST'
MEMCACHED_PORT = 'MEMCACHED_PORT'

# MongoDB Configurations
MONGODB_HOST = 'MONGODB_HOST'
MONGODB_PORT = 'MONGODB_PORT'

MESSAGE = 'message'
ERROR = 'error'
CAUSE = 'cause'
