# App Configurations
APP_RELOAD = 'APP_RELOAD'
APP_HOST = 'APP_HOST'
APP_PORT = 'APP_PORT'
APP_WORKERS = 'APP_WORKERS'

# Memcached Configurations
MEMCACHED_HOST = 'MEMCACHED_HOST'
MEMCACHED_PORT = 'MEMCACHED_PORT'

# MongoDB Configurations
MONGODB_HOST = 'MONGODB_HOST'
MONGODB_PORT = 'MONGODB_PORT'
MONGODB_DB = 'MONGODB_DB'
MONGODB_COLLECTION = 'MONGODB_COLLECTION'

LONG_URL = 'long_url'
SHORT_URL = 'short_url'
PREFERRED_SHORT_URL = 'preferred_short_url'
MESSAGE = 'message'
ERROR = 'error'
CAUSE = 'cause'
FROM = 'from'
