version: '2'

services:
  memcached:
    image: docker.io/bitnami/memcached:1
    ports:
      - '11211:11211'
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_MAX_CONNECTIONS=2000
      - MEMCACHED_MAX_ITEM_SIZE=8388608
      - MEMCACHED_USERNAME="admin"
      - MEMCACHED_PASSWORD="@dm!nP@ss"
