apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: r4rajat/url-shortener
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5000
          env:
            - name: MEMCACHED_HOST
              value: "memcached-service"
            - name: MONGODB_HOST
              value: "mongo-service"
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  labels:
    app: url-shortener
spec:
  type: LoadBalancer
  ports:
   - port: 5000
  selector:
   app: url-shortener