apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: docker.io/bitnami/memcached:1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 11211
          env:
            - name: MEMCACHED_CACHE_SIZE
              value: "128"
            - name: MEMCACHED_MAX_CONNECTIONS
              value: "2000"
            - name: MEMCACHED_MAX_ITEM_SIZE
              value: "8388608"
---
apiVersion: v1
kind: Service
metadata:
  name: memcached-service
  labels:
    app: memcached
spec:
  type: ClusterIP
  ports:
   - port: 11211
     targetPort: 11211
  selector:
   app: memcached